### ISSUE TITLE
computation of the metrics

### ISSUE THREAD

**Issue by friguzzi** [symbolic-kg/PyClause#7]
Hi all,
I'm trying to compute the KGC metrics using Prolog and I'm finding differences in the results I find with those of PyClause.
I understand that PyClause finds only the first 100 possible answers for a KGC query.
But sometimes I have found that PyClause misses some answers.
For example, on the WN18RR dataset, for triple 10551265 _synset_domain_topic_of 15259284 it finds 16 answers while according to my calculations there are 18. The missing ones are 06371413 and 09587565.
You can find the data and code used in my experiments at https://github.com/friguzzi/lp4kg/tree/main/wn18rr 
In particular, the rule set is https://github.com/friguzzi/lp4kg/blob/main/wn18rr/theory.txt and the ranking file is https://github.com/friguzzi/lp4kg/blob/main/wn18rr/ranking-file.txt
The code used to produce it is at https://github.com/friguzzi/lp4kg/blob/main/wn18rr/ranking.py
The extra answers were found using my implementation in Prolog that is available in https://github.com/friguzzi/lp4kg/tree/main/wn18rr/rank

Best
Fabrizio

**Comment by Nzteb** [comment]
Hey Fabrizio,

regarding the only first 100 possible answers, you can also set the topk parameter of RankingHandler and QAHandler to have more (or all possible). But it is indeed not related to your question, given that we predict less.

I can replicate the candidates from your ranking file with your code but not the scores. In the code you provided, you load a rule set with a different name _rules = f"out_sup_conf_novalid.txt"_ . Is it maybe a different rule set and that is why my scores are different?

Apart from that, I have the same 16 candidates as in your ranking for the triple (tail direction) and not 18.

When I modify your code and add
`options.set("ranking_handler.filter_w_data", False)` ,
then I get 17 answers. The missing 06371413 is included now.
The option turns off filtering with true triples from train. We always filter with everything possible in the default options as it aligns with the KGC protocols. It turns out that  10551265 _synset_domain_topic_of 06371413 exists in train.

For the the other candidate, it is hard to go backwards and say why it is not a predicted answer. I'm not familiar with the Prolog implementation you provided. Do you have a way to retrieve the rule and body grounding(s) that lead to the answer?

If I had to guess, I would go this route (apart from having a bug, of course):
When browsing through your rules, for these longer cyclical rules on WNRR, often what we call object identity becomes relevant. We do not allow 2 distinct variables to be substituted with the same entity when looking for body groundings while performing rule application. We describe this (very vaguely) here:  https://pyclause.readthedocs.io/en/latest/conceptual/rules.html#symbolic-rules 
How does your implementation handle this?  If this could be the core of the problem, I could provide a minimal example with one rule and only a few triples and we could compare based on this (we don't have an option to turn off this behavior).

Best

Patrick

**Comment by friguzzi** [comment]
HI Patrick,
thanks! The problem is with object identity. 
In fact, the rulesthat match for the other answer are
```
10254	89	0.00867953969182758	_synset_domain_topic_of(X,Y) <= _instance_hypernym(X,A), _instance_hypernym(B,A), _instance_hypernym(B,Y)
26853	1	3.7239786988418424e-5	_synset_domain_topic_of(X,Y) <= _instance_hypernym(X,A), _hypernym(A,B), _hypernym(Y,B)
```
with the grounding
```
_synset_domain_topic_of(10551265,09587565):
[0.00867954-(_instance_hypernym(10551265,09587565),_instance_hypernym(09601571,09587565),_instance_hypernym(09601571,09587565)),
0.00867954-(_instance_hypernym(10551265,09587565),_instance_hypernym(09590205,09587565),_instance_hypernym(09590205,09587565)),
0.00867954-(_instance_hypernym(10551265,09587565),_instance_hypernym(10172793,09587565),_instance_hypernym(10172793,09587565)),
0.00867954-(_instance_hypernym(10551265,09587565),_instance_hypernym(10551265,09587565),_instance_hypernym(10551265,09587565)),
0.00867954-(_instance_hypernym(10551265,09587565),_instance_hypernym(10550951,09587565),_instance_hypernym(10550951,09587565)),
3.72398e-5-(_instance_hypernym(10551265,09587565),_hypernym(09587565,09483738),_hypernym(09587565,09483738))]
```
What is the rationale for object identity?

Best
Fabrizio

**Comment by Nzteb** [comment]
I see, great that we found it!

The implementation of PyClause in general inherits the OI behavior of AnyBURL which was built under the goal of being a strong symbolic baseline for KGC. So in general, it will help the predictive performance.  

We, for example, also allow for recursive rules. Stuff can break here in terms of a rule simply predicting an existing triple in the base KG (train) because it could be part of a body grounding.

Or in other cases, some body grounding being composed of three times the same triple. For example,  in one of the groundings you showed: `(_instance_hypernym(10551265,09587565),_instance_hypernym(10551265,09587565),_instance_hypernym(10551265,09587565)),`

And I think it turned out that these things were harming performance for the particular application. In terms of a full logic formalism/implementation, which AnyBURL/PyClause are not about, I do not know about the pros vs. cons.

Best

Patrick

**Comment by friguzzi** [comment]
Hi Patrick,
I checked: by adding object identity to my code I get the same results, thanks. 

To obtain all the answers with PyClause I used:
options.set("ranking_handler.topk", 100000000)
Is there another way?

Another question: when computing the ranking, how do you deal with answers with the same score?
I see this option
```
# choose between "random" / "frequency"
# frequency: if two candidates can not be discriminated because they are predicted
# by exactly the same rules; discriminate them according to their number of appearances
# in the 'data' argument KG (e.g., the train data)
# random: random tie handling
tie_handling: "frequency"
```
Do you mean that you count the frequency of an entity appearing as head or tail in train triples?
Why don't you use average ranking that assigns the average rank of the group of answers with the same score?
Isn't this what is used by embedding methods?

Thanks again
Fabrizio

**Comment by Nzteb** [comment]
Hi Fabrizio,

At the moment, there is no more elegant way to set topk. Ill add it to the enhancement list, it only needs a small adjustment.

Regarding answers with the same scores.

> Do you mean that you count the frequency of an entity appearing as head or tail in train triples?

Yes.

> Isn't [average ranking] what is used by embedding methods?

Yes. See, e.g.,  [LibKGE](https://github.com/uma-pi1/kge).

> Why don't you use average ranking that assigns the average rank of the group of answers with the same score?

This answer is  a bit more complicated. In general, we put tie handling conceptually to the model side and not to the evaluation side. That means, the function that calculates the ranking-based metrics only cares about the candidate ordering given by the model, independent of any scores. It also means, the model already has to make a decision about tie handling.

One reason why we do it like that is the MAXPLUS heuristic. It discriminates answers by lexicographically comparing the lists of confidences of their predicting rules. But it will still only output as score for one answer the highest confidence under its predicting rules. So if two answers have the same score, there might still be a reason (in terms of the heuristic) why one is ranked on top of the other.

So real ties are handled on the rule application side and for Noisy-or variants it is needed already when two answers have the same score. On this side, when answers are computed and ranked, we do not know if an answer is true or false. One of the tie handling options is "random": The ordering of the answers that have ties are random  e.g.,[[1]](https://aclanthology.org/2020.acl-main.489.pdf). In expectations this is the same as the 'average' protocol that was mentioned above. And the option "frequency" is as described above. We chose this as default because of its deterministic nature (but it falls back to random, if the answers have also the same counts).

In general, the observed differences regarding the metric values are in the ranges of affecting the 4th or 5th position of an MRR written as  "49.5XYZ". So they do not alter the qualitative results and most often do not change the MRR value when it is written with three numbers "49.5". I think that "frequency" will also be a bit worse than "random" but I would need to test it.

Best

**Comment by friguzzi** [comment]
Thanks Patrick, all is clear now and I can reproduce your results with my code.
